[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "http://*jatamttoingenieriahseq.com/*"
  to = "https://jatamttoingenieriahseq.com/:splat"
  status = 301
  force = true
